### ISSUE TITLE
indent errors when running

### ISSUE THREAD

**Issue by Manuel5cc** [Hemisphere-Project/HLS-server#1]
I am trying to run the segmenter and I get this error:

```
Traceback (most recent call last):
  File "./segmenter", line 271, in <module>
    main(sys.argv[1:])
  File "./segmenter", line 261, in main
    segmenter(inputfile=inputfile, dryrun=variantonly, urlprefix=urlprefix)
  File "./segmenter", line 157, in segmenter
    import presets
  File "/mnt/c/Users/Manue/HLS-segmenter/presets.py", line 57
    PROFILES['5-high'] = {
    ^
IndentationError: unexpected indent
```

**Comment by Maigre** [comment]
Hi,
Did you edit the file ?
This is python so indentations are really sensitive,
try to re-indent properly every lines, or you could also use an atom plugin to help 
like https://atom.io/packages/python-indent
Let me know !
Best,
Thomas

**Comment by Manuel5cc** [comment]
I didn't modify any files. I'm not sure of what happened the first time, but I've tried cloning the git again and it worked perfectly.

**Comment by Manuel5cc** [comment]
I only uncommented high and HD profiles to make them work. Was I supposed to do anything else?

**Comment by Maigre** [comment]
When you uncommented it might have break the indentation:
there is a # and an extra space after on each commented line so you must
remove both # and the following space to uncomment:
The error you see is because you removed only the # then PROFILES['5-high']
had a empty space before which python interpret as a indent which is not
supposed to be here.

I did uncomment properly both profiles, so if you re-clone again now it
should work with high and hd profiles.
Let me know !
Best

**Comment by Manuel5cc** [comment]
Yep now it works! thx!
